packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  workerd: true

overrides:
  '@esbuild-kit/core-utils>esbuild': ^0.28.0

patchedDependencies:
  ammo.js@0.0.2: patches/ammo.js@0.0.2.patch
